Store Streamer Messages in Redis
near/queryapi pull request #241
Opened 2023-09-27 19:03 UTC by darunrs

2023-09-27 21:03 UTC, darunrs commented
https://github.com/near/queryapi/issues/204

2023-10-02 19:18 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
This if loop was allowing null values through, which was leading to them being replaced by {}. Not sure if this is problematic or a non-issue. In any case, I updated the if statement to retain null values and was able to confirm my implementation does match what S3 returns.

2023-10-02 21:01 UTC, gabehamilton commented on runner/src/indexer/indexer.ts
> +    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
Nice. This code was copied from https://github.com/near/near-lake-framework-js/blob/eb35cf836c03c9cd925d4b7c6dcb29b52aa757fa/src/utils.ts#L35 
Looks like it got the same update at some point.

2023-10-02 21:01 UTC, gabehamilton reviewed
👍

2023-10-02 22:07 UTC, morgsmccauley requested changes
Great first start :) I've left a few comments. Can you please also link the issue?

2023-10-02 22:07 UTC, morgsmccauley commented on runner/src/metrics.ts
> +});
```suggestion
const CACHE_HIT = new promClient.Counter({
  name: 'queryapi_runner_cache_hit',
  help: 'Number of times cache hit was successful',
  labelNames: ['type', 'key']
});
```
It might make sense to make this more generic, and add a new dimension/label for the key which was hit/missed. That way we use this more globally.

Same for above

2023-10-02 22:07 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +        METRICS.CACHE_HIT_STREAMER_MESSAGE.labels(isHistorical ? 'historical' : 'realtime').inc(); // increment the cache hit counter
```suggestion
        METRICS.CACHE_HIT_STREAMER_MESSAGE.labels(isHistorical ? 'historical' : 'real-time').inc(); // increment the cache hit counter
```
We use this for other metrics, let's stay consistent with that.

2023-10-02 22:07 UTC, morgsmccauley commented on runner/package.json
> +    "@aws-sdk/client-s3": "^3.414.0",
nice

2023-10-02 22:07 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +      if (cachedMessage) { // Cache hit on streamer message
Nit: It's best to add comments when the intent isn't super obvious, here and below I think the code speaks for itself, I think the comments are unnecessary :)

2023-10-02 22:18 UTC, darunrs commented
Tracking Issue: https://github.com/near/queryapi/issues/262
Parent Issue: https://github.com/near/queryapi/issues/204

2023-10-03 00:06 UTC, darunrs commented on indexer/storage/src/lib.rs
> +    redis::cmd("SETEX")
Yep that works. I've implemented it under set(). I went with using an optional.

2023-10-03 00:07 UTC, darunrs commented on indexer/queryapi_coordinator/src/main.rs
> +            context.chain_id,
Ah gotcha. In that case, I'll remove it.

2023-10-03 00:10 UTC, darunrs commented on indexer/queryapi_coordinator/src/utils.rs
> +    let mut message_value: Value = serde_json::from_str(&json_str).unwrap();
Thanks for the info! I've updated it to not use unwrap.

2023-10-03 00:21 UTC, darunrs commented on indexer/queryapi_coordinator/src/utils.rs
> +) -> Value {
That's indeed a better name. And gotcha, I'll have it return serialized to string.

2023-10-03 00:26 UTC, darunrs commented on indexer/queryapi_coordinator/src/main.rs
> +            context.chain_id,
I'll have to remove it from Runner too. I'm guessing we'll have a different runner instance which is handling requests?

2023-10-03 17:09 UTC, darunrs commented on runner/src/metrics.ts
> +});
That's a good idea. I'll implement it.

2023-10-03 17:13 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +      if (cachedMessage) { // Cache hit on streamer message
True! I'll remove it.

2023-10-05 19:13 UTC, morgsmccauley reviewed
Couple small comments but otherwise looks good!

2023-10-05 19:13 UTC, morgsmccauley commented on indexer/queryapi_coordinator/src/main.rs
> +        ),
Nit: Might be good to extract this to a method like we have for the others in `storage/lib.rs`
```rust
pub fn generate_historical_stream_key(prefix: &str) -> String {
    format!("{}:historical:stream", prefix)
}
```

2023-10-05 23:23 UTC, darunrs commented on indexer/storage/src/lib.rs
> +    tracing::debug!(target: STORAGE, "SET: {:?}: {:?} {:?}", key, value, exp_to_print);
Good idea! Will do.

2023-10-05 23:45 UTC, morgsmccauley approved these changes
LGTM!

2023-10-05 23:50 UTC, merged