Pre-Fetch Historical Streamer Messages
near/queryapi pull request #269
Opened 2023-10-05 00:54 UTC by darunrs

2023-10-05 18:50 UTC, darunrs commented
https://github.com/near/queryapi/issues/264

2023-11-03 04:34 UTC, morgsmccauley requested changes
Really great start on this - left a couple comments :)

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +    const messages = await redisClient.getNextStreamMessage(streamKey, preFetchCount);
`getNextStreamMessage` will, by default, return messages starting from the beginning of the stream. Instead, we should maintain a 'current position/id' and feed that in. Without it, we'll be re-reading the same messages and putting them on to the queue.

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +    const queueMessage = await queue.shift();
We might not want to `shift()` right away - removing _before_ we successfully execute means that the message will be lost if the executing fails. And since it wouldn't be deleted, I guess it would then be put back on to the queue but out of order.

Instead we should just read the first element, and then `.shift()` after success.

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +    const messages = await redisClient.getNextStreamMessage(streamKey, preFetchCount);
Maybe we should [`BLOCK`](https://redis.io/commands/xread/) here rather `sleep`ing, that would mean we are reacting as quick as possible to new messages - could you experiment with that please?

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +      await sleep(300); // Wait for more messages in array to process
Nit: lets remove these comments and the others, the code is descriptive enough as is :)

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +      await sleep(300); // Wait for more messages in array to process
Also let's experiment with smaller numbers to increase reaction speed.

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +let isHistorical = false;
Nit: Global variables like this are convenient, but generally discouraged because it opens up the possibility for this to be changed by many different things, which can become difficult to track.

Let's scope this to `main()` or ideally, closer to where it is used.

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +const queue: Array<Promise<QueueMessage>> = [];
Same comment here around global variables - let's put this in `main`

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +    try {
Let's wrap as much as possible with this `try` block to avoid errors escaping this context, ideally anything that is `await`ed, should be wrapped.

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +      fetchAndQueue(queue, Number(message.block_height), id);
```suggestion
      queue.push(transformStreamerMessageToQueueMessage(blockHeight, id));
```
Nit: I think this code is simple/descriptive enough to just be inlined?

2023-11-03 04:34 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +async function transformStreamerMessageToQueueMessage (blockHeight: number, streamId: string): Promise<QueueMessage> {
Nit: I feel like `transform` doesn't fully capture the intent here, how about `generateQueueMessage`, as it also has some logic to fetch the streamer message. Probably being pedantic here 😅

2023-11-03 17:30 UTC, darunrs commented on runner/src/lake-client/lake-client.ts
> +  async fetchStreamerMessage (blockHeight: number, isHistorical: boolean): Promise<StreamerMessage> {
You're correct. I forgot to polish up this new class after migrating all the code to it. I'll fix it up!

2023-11-03 17:33 UTC, darunrs commented on runner/src/metrics.ts
> +const USER_CODE_EXECUTION_DURATION = new Histogram({
I suppose that's fair. I'll remove this and make a new issue around instrumentation, if it doesn't already exist.

2023-11-03 17:36 UTC, darunrs commented on runner/src/metrics.ts
> +});
I've rebased. It shows up as new because I moved the metrics around to be in order of when they are recorded. This was to make it easier to understand all the metrics at a glance.

2023-11-03 17:41 UTC, darunrs commented on docker-compose.yml
> +  grafana:
I guess on one hand I do agree and on another I don't. From a indexer developer perspective, definitely agree. I know we have a goal of eventually supporting local development of indexers and this docker file was a step in that direction. If our goal is to keep this file oriented for that goal, we probably don't need metrics things. On the other hand, I think having metrics would be very helpful to anyone intending to contribute to the repo itself, whether in our team or not. I'm personally leaning towards keeping it in as someone can simply comment out this bit if they don't want it. And if it's running, the impact should be minimal, I think. Let me know if your thoughts align or not!

2023-11-03 17:43 UTC, darunrs commented on runner/src/lake-client/lake-client.ts
> +    if (!isHistorical) {
I figured this was the case but I didn't want historical to pollute the cache miss metric since every historical block would fail to hit cache. I guess I can do something like only post the cache miss if it's not historical, but since I already have an if statement, I might as well put it all in there.

2023-11-03 19:38 UTC, darunrs commented on runner/src/lake-client/lake-client.ts
> +        METRICS.CACHE_HIT.labels().inc();
So, I actually removed the label since the label was if it's real-time or historical. Except, we aren't using the cache if it's historical so I figured there's no label to set and did not set any. Do you think I should still set that information anyway? Should I add both indexer name as well as type? My graphs in grafana got messy when I did so but perhaps that can be fixed by adjusting the query. Let me know what you think. In the meantime, I'll play around with it and if I can get it to look right while adding the labels, I'll do so, and adjust dev's graph when the PR goes through if we end up setting them.

2023-11-03 21:04 UTC, darunrs commented on runner/src/stream-handler/worker.ts
> +    const messages = await redisClient.getNextStreamMessage(streamKey, preFetchCount);
Yep you're right. I'll look over the process and make sure it's consistent. I think retaining the latest stream ID read and not shifting the queue should be sufficient.

2023-11-03 22:14 UTC, darunrs commented on runner/src/stream-handler/worker.ts
> +    const messages = await redisClient.getNextStreamMessage(streamKey, preFetchCount);
Will do!

2023-11-03 22:52 UTC, darunrs commented on runner/src/stream-handler/worker.ts
> +let isHistorical = false;
A few of them I was able to move easily into one of the functions. But, some of the others like redis client, lake client, and isHistorical are used all over. I moved them into a single object called WorkerContext and will pass that into function calls instead. I couldn't find a way to make private global variables so I don't think I can do anything to make them accessible like a class variable through this. Let me know if there's a cleaner way of doing this!

2023-11-03 23:11 UTC, darunrs commented on runner/src/stream-handler/worker.ts
> +async function transformStreamerMessageToQueueMessage (blockHeight: number, streamId: string): Promise<QueueMessage> {
Pedantic is fine! Might as well get a good name going the first time. I also like that name. Changed!

2023-11-06 21:35 UTC, darunrs commented
I'm still experimenting with the blocking values. In the meantime, I released the changes I've made so far. Let me know what you think!

2023-11-06 23:21 UTC, darunrs commented
I ran roughly 5000 messages of sweat blockheight before and after the blocking commit and I can visually see an improvement. Left is with the commit and right is without it. Block wait time is lower and less spread out. Although, it was already low enough to not impact much anymore anyway. Execution duration and overhead latency spread is tighter too. The BPS curve is more linear and the peak was higher too. In any case, it seems the commit helps a fair bit. I will try again but this time run all indexers simultaneously. And finally, I'll check running coordinator and runner together (Although I wont be able to see metrics for that since coordinator's metrics server would block runners'. I plan to look into that later. 

<img width="1165" alt="image" src="https://github.com/near/queryapi/assets/22734869/67a14e8d-cfc7-4de4-8bfb-3d74fbc52871">

2023-11-07 21:31 UTC, morgsmccauley commented on runner/src/lake-client/lake-client.ts
> +    this.redisClient = redisClient;
This are assigned automatically when you declare the `private readonly` above - you can remove them

2023-11-07 21:31 UTC, morgsmccauley commented on runner/src/lake-client/lake-client.ts
> +        METRICS.CACHE_HIT.labels().inc();
Nah seems like it's not needed, in which case you can remove the `.label()` call

2023-11-07 21:31 UTC, morgsmccauley commented on runner/src/redis-client/redis-client.ts
> +    streamId = this.SMALLEST_STREAM_ID,
```suggestion
    streamId = this.SMALLEST_STREAM_ID,
    count = 1,
```
Can we swap these, `count` seems less likely to change that `streamId`, so putting it after means we don't need to define `count` every time

2023-11-07 21:31 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +  const streamType = workerContext.redisClient.getStreamType(streamKey);
This is already in the `workerContext` right?

2023-11-07 21:31 UTC, morgsmccauley commented on runner/src/stream-handler/worker.ts
> +    const preFetchCount = await waitForQueueSpace(workerContext);
```suggestion
    const preFetchCount = HISTORICAL_BATCH_SIZE - workerContext.queue.length;
    if (preFetchCount <= 0) {
      await sleep(100);
      continue;
    }
```

Seems simpler just to add this here rather than creating an interval?

2023-11-07 22:17 UTC, darunrs commented on runner/src/redis-client/redis-client.ts
> +    streamId = this.SMALLEST_STREAM_ID,
Ah good point. Switched!

2023-11-07 22:19 UTC, darunrs commented on runner/src/stream-handler/worker.ts
> +  const streamType = workerContext.redisClient.getStreamType(streamKey);
Ah oops. it is! Fixed!

2023-11-08 21:02 UTC, darunrs commented
I did some more experimentation and found that blocking does in fact block both loops, not jsut the producer. As a result, once no stream messages are present, execution of the functions becomes slow as the xread blocks the whole thread for the blocking duration. Removing it returned the speed improvements. 

In addition, I ran a test against sweat_blockheight where I appended the block-height of each stream message to one file and then appended the block height to a second file after runFunction is called. I diff'd the two files and found no differences. This was enough to verify that every message in the stream is seen and processed exactly once.

2023-11-08 21:21 UTC, morgsmccauley approved these changes
LGTM - great work :)

2023-11-08 21:22 UTC, morgsmccauley commented
Just need to fix failing tests

2023-11-08 22:23 UTC, merged