Fix loading a schema from registry
near/queryapi pull request #489
Opened 2024-01-05 15:40 UTC by jl-santana

Link to the issue [here](https://github.com/near/queryapi/issues/482)

Changes on this PR
- Refactored Editor file, 
   -- remove side effects from reformatAll function, solving the main problem of the issue
   -- simplified useEffects with logic related to loading the schema, separating concern and focusing them on only one task
   -- remove dead code
   -- simplified other functions

- Refactored logic to validate the schema
  -- only validate schemas different from the default

- Fixed issue when generating types

https://github.com/near/queryapi/assets/15988846/d926db10-e347-498e-bb63-759dc5868f09

2024-01-05 18:07 UTC, darunrs commented on frontend/src/utils/validators.js
> +    return { data: schema, error };
What is schema in this context? DId you mean to return code or null?

2024-01-05 18:34 UTC, roshaans requested changes
Overall good refactoring and simplification of logic!

Just some side effects that these changes had in the behavior of the editor which we should resolve.

2024-01-05 18:34 UTC, roshaans commented on frontend/src/components/Editor/Editor.jsx
>        setError("Oh snap! We could not format your code. Make sure it is proper Javascript code.");
This part of the code does not seem to be hit in this version 

Old in Prod currently: 
![old_code](https://github.com/near/queryapi/assets/25015977/1707fafa-4f77-4ab2-a5f6-a1a043389910)

This   PR: 
![new_code](https://github.com/near/queryapi/assets/25015977/aa270a1e-890a-452e-b941-7320ec0d85d3)

2024-01-05 18:34 UTC, roshaans commented on frontend/src/components/Editor/Editor.jsx
>    async function handleFormating() {
Seems like the reload button is not properly working anymore: 

![reload_doesnt_work](https://github.com/near/queryapi/assets/25015977/74c3591d-de0d-47b1-879f-fdaa1e71f5e4)

2024-01-05 19:35 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> +  useEffect(() => {
Not sure exactly which useEffect you are referring here, the one ending in the line 120, validate the schema the first time we pull the data from the blockchain. The one starting in the line 122 validate the schema and the code every time a user change a tab.

2024-01-05 19:39 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> +      if (schemaError) setError("There is an error in your schema. Please check the console for more details")
makes sense

2024-01-05 19:41 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> -  useEffect(() => {
I just refactored this useEffect, the effect is covered in the line 122

2024-01-05 19:47 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> -            handleEditorMount={handleEditorMount}
That was dead code, it was being used
<img width="372" alt="Screenshot 2024-01-05 at 2 45 34 PM" src="https://github.com/near/queryapi/assets/15988846/b63d8a90-838d-431c-9e4d-43068f5257bb">

2024-01-05 19:49 UTC, jl-santana commented on frontend/src/components/Editor/ResizableLayoutEditor.jsx
>    blockView,
That was exactly what I planned to ask you for refactoring, but I didn't want to cover it on this PR, neither was necessary for the solution of this issue. But good to know.

2024-01-05 19:52 UTC, jl-santana commented on frontend/src/utils/pgSchemaTypeGen.js
> +		const statements = Array.isArray(schemaSyntaxTree) ? schemaSyntaxTree : [schemaSyntaxTree];
It was. The function astify return either an array of an object if is just un statement. So for the code to serve the purpose in both cases, I made sure we were always processing an array of statements.

`astify(sql: string, opt?: Option): AST[] | AST;`

2024-01-05 19:53 UTC, jl-santana commented on frontend/src/utils/pgSchemaTypeGen.js
> +		for (const statement of statements) {
Thanks man

2024-01-05 19:56 UTC, jl-santana commented on frontend/src/utils/validators.js
> +    return { data: schema, error };
Good catch

2024-01-05 19:57 UTC, jl-santana commented on frontend/src/utils/validators.js
> +    return { data: schema, error };
yes, that's same error @roshaans was referring to in the comment before. Good catch

2024-01-05 20:01 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> +  const debouncedValidateSQLSchema = useDebouncedCallback((_schema) => {
No really, this validation function is called every time a user types something, so with this debounce we wait for half a second (usually bigger than the time it takes to a person to type different keys). So it only triggers the validation after the user stop typing.

2024-01-05 20:55 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
>        setError("Oh snap! We could not format your code. Make sure it is proper Javascript code.");
Good catch, there was an error in 259, i was naming the right exports from the function.

2024-01-05 20:55 UTC, jl-santana commented on frontend/src/utils/validators.js
>  export async function validateSQLSchema(schema) {
no need for

2024-01-05 21:02 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> -  function handleEditorMount(editor) {
The code/schema is working properly yes. Below is a video with all the cases. This would be nice to be handled by an e2e test

2024-01-05 21:02 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
> -  function handleEditorMount(editor) {
Uploading Screen Recording 2024-01-05 at 3.59.18 PM.mov…

2024-01-05 21:12 UTC, darunrs commented on frontend/src/components/Editor/Editor.jsx
> -  function handleEditorMount(editor) {
Definitely would be nice. We're starting to prioritize e2e testing for QueryAPi as a whole. I'll be starting on that for the backend this month. A similar effort on the frontend would be good to do, for sure.

2024-01-05 21:13 UTC, darunrs commented on frontend/src/components/Editor/Editor.jsx
> +  const debouncedValidateSQLSchema = useDebouncedCallback((_schema) => {
Ahh I see. This wasn't in a useEffect, from what I could tell on the compare screen so I thought it was one of those only-on-init calls. 

In that case, this is a great change!

2024-01-05 22:18 UTC, roshaans requested changes
One more minor change, but I am happy to approve right after! Overall great changes 💯

2024-01-05 22:18 UTC, roshaans commented on frontend/src/components/Editor/Editor.jsx
>      }
We should reset the errors if there are no more errors in formatting. Or upon reseting of the code, we should set the errors to null. 

![reset_errors](https://github.com/near/queryapi/assets/25015977/cfb86dfe-4570-45b3-a33b-f848f6f9d49a)

2024-01-06 03:27 UTC, jl-santana commented on frontend/src/components/Editor/Editor.jsx
>      }
Totally. A better UX after that.

2024-01-06 03:54 UTC, roshaans approved these changes
LGTM! 💯

2024-01-08 15:03 UTC, merged