541 update the frontend to dis allow use of this filter
near/queryapi pull request #567
Opened 2024-02-16 21:51 UTC by Kevin101Zhang

added the * filter for contracts.
A valid contract is defined as 

  const isWildcard = accountId.trim() === "*" || accountId.trim() === "*.near";
  const isLengthValid = accountId.length >= 2 && accountId.length <= 64;
  const isRegexValid = CONTRACT_NAME_REGEX.test(accountId);

  return isWildcard || (isRegexValid && isLengthValid);
  
note: CONTRACT_NAME_REGEX must end with .near (case sensitive)

Added jest to support function testing.

It seems there's a problem getting Babel and the VM to work smoothly together. I'm going to dig deeper into it. Right now, I'm adjusting the test file to recreate the functions instead of using the usual require/import method, which seems to cause trouble with the VM code. It does mean there's some duplicated code in the testing files, but the test work.

2024-02-16 23:10 UTC, darunrs reviewed
Some comments on the updated regex, and testing methodology. Great job adding jest here!

2024-02-16 23:10 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +function validateContractId(accountId) {
You should always import anything you are testing, rather than repeating. The last thing you want is for the thing you intended to test to diverge from the code you copied here.

2024-02-16 23:10 UTC, darunrs commented on frontend/src/constants/RegexExp.js
> +export const CONTRACT_NAME_REGEX = /^(?:\*|(?:[a-z\d]+[-_])*[a-z\d]+)(?:\.(?:\*|(?:[a-z\d]+[-_])*[a-z\d]+))*\.near$/i;
This already supported *.near and other things. Let's try to change it as little as possible, since it seems to have already been working. Let's just make the safe change of allowing * in addition to whatever we currently have!

2024-02-16 23:10 UTC, darunrs commented on frontend/jest.config.js
> +// jest.config.js
Nice job adding unit tests here!

2024-02-16 23:38 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +  const isLengthValid = accountId.length >= 2 && accountId.length <= 64;
Found this as a start: https://nomicon.io/DataStructures/Account

2024-02-19 18:13 UTC, Kevin101Zhang commented on frontend/src/components/Editor/__tests__/validator.test.js
> +function validateContractId(accountId) {
I mentioned in the description there are some issues with Babel and the VM to work smoothly together. Will try again with the import later on

2024-02-19 18:13 UTC, Kevin101Zhang commented on frontend/src/constants/RegexExp.js
> +export const CONTRACT_NAME_REGEX = /^(?:\*|(?:[a-z\d]+[-_])*[a-z\d]+)(?:\.(?:\*|(?:[a-z\d]+[-_])*[a-z\d]+))*\.near$/i;
ok!

2024-02-20 23:04 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +    const invalidWildcard = '*invalid.near';
Right so as discussed in the meeting, we allow star at the beginning only separated by a `.`. E.g. `*.near`, `*.tg`, `*.some.sub.account` but NOT `some.*.account`, `account.*`, `someone.*` or `*near`. We also allow just `*`.

2024-02-21 02:00 UTC, darunrs reviewed
Mostly looks good to me. 

I just want to clarify once more that we want to support* as that seems correct to me. I checked with Pavel and he confirmed what I thought about supporting `*` alone. 

Also dropped a suggestion for fixing that babel issue. If it works, awesome.  If not, no big deal, we can defer it. Leave a TODO in the test file to replace with imports later.

2024-02-21 02:00 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +const CONTRACT_NAME_REGEX = RegExp(/^(([a-z\d]+[-_])*[a-z\d]+(\.([a-z\d]+[-_])*[a-z\d]+)*\.([a-z\d]+)|([a-z\d]+))$/);
Can you try adding a babel.config.js to the frontend folder and trying imports again? I feel like that might work? 

Put this in the config:
`module.exports = {presets: ['@babel/preset-env']}`

2024-02-21 02:00 UTC, darunrs commented on frontend/src/utils/validators.js
> +  isWildCard ? accountId = accountId.slice(2) : null;
Could be re-written as 
`accountId = isWildCard ? accountId.slice(2) : accountId;`

I think having a set operation in the middle is a wee bit awkward.

2024-02-21 02:00 UTC, darunrs commented on frontend/src/constants/RegexExp.js
> +export const CONTRACT_NAME_REGEX = RegExp(/^(([a-z\d]+[-_])*[a-z\d]+(\.([a-z\d]+[-_])*[a-z\d]+)*\.([a-z\d]+)|([a-z\d]+))$/);
Nice job on the regex!

2024-02-21 03:07 UTC, pkudinov commented on frontend/src/components/Editor/__tests__/validator.test.js
> +  const isWildCard = WILD_CARD_REGEX.test(accountId);
I think WILD_CARD_REGEX will match `abc*.near` as well, and we only need it to match `*.a.b.c.near` type of account

2024-02-21 03:11 UTC, pkudinov requested changes, later dismissed

2024-02-21 03:11 UTC, pkudinov commented on frontend/src/components/Editor/__tests__/validator.test.js
> +    const invalidWildcard = '*invalid.near';
Indeed, `*` should be a valid filter, as we discussed during the call

2024-02-21 19:58 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +  const isWildCard = WILD_CARD_REGEX.test(accountId);
This is true. We probably need something more like `/^\*./`

2024-02-21 21:33 UTC, Kevin101Zhang commented on frontend/src/components/Editor/__tests__/validator.test.js
> +const CONTRACT_NAME_REGEX = RegExp(/^(([a-z\d]+[-_])*[a-z\d]+(\.([a-z\d]+[-_])*[a-z\d]+)*\.([a-z\d]+)|([a-z\d]+))$/);
The problem was specifying babel to only run on test as babel fails on our actual production code. Happy to sync to try to resolve this

2024-02-21 21:36 UTC, Kevin101Zhang commented on frontend/src/components/Editor/__tests__/validator.test.js
> +  const isWildCard = WILD_CARD_REGEX.test(accountId);
WILD_CARD_REGEX is testing if the string starts with '*.'
The code right now suceeds for *.a.b.c.near and fails for abc*.near.

2024-02-21 22:17 UTC, darunrs commented on frontend/src/components/Editor/__tests__/validator.test.js
> +  const isWildCard = WILD_CARD_REGEX.test(accountId);
Oh no I didn't say we shouldn't. I said we should, even if the validate function would reject it anyway.

2024-02-21 22:58 UTC, darunrs approved these changes
Looks good to me. There's a merge conflict but otherwise, should be good. 

Add a comment above the original validate functions that they're duplicated in the test files due to a Babel config issue, and a TODO to address that. 

Also, can you rename the PR to something like `feat: Support Wildcard filters and * contract filters`?

2024-02-26 19:03 UTC, merged