feat: prototyped new logs schema
near/queryapi pull request #608
Opened 2024-03-19 20:10 UTC by Kevin101Zhang

Integrated new logs schema for. We are writing to both default/public/indexer_logs_entries and provisioning a new table on new indexers under the user's provisioned database and respective schema.

https://www.loom.com/share/ff21d7099cac403d9152c905f7e4ddcc?sid=5828ae99-377b-4510-ac8c-76c02fd232f2

2024-03-19 20:16 UTC, Kevin101Zhang commented
cases until completion:

1. cron statements (currently commented out)
2. add cases where user's indexer is already provisioned and we must provision only the logs table
3. update provision.test.ts & hasura-client.test.ts

2024-03-19 20:18 UTC, pkudinov requested changes, later dismissed

2024-03-19 20:18 UTC, pkudinov commented on runner/src/indexer/indexer.ts
> +            `mutation InsertLogs($block_height: numeric, $log_date: date, $log_level: String, $log_type: String, $message: String) {
This must be done through SQL query – we want to avoid using GraphQL for such operations.

2024-03-19 20:25 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +            `mutation InsertLogs($block_height: numeric, $log_date: date, $log_level: String, $log_type: String, $message: String) {
ok I will change it to a sql equivalent

2024-03-19 20:25 UTC, pkudinov commented on runner/src/indexer/indexer.ts
> +            `mutation InsertLogs($block_height: numeric, $log_date: date, $log_level: String, $log_type: String, $message: String) {
And we should make batch INSERT calls to reduce the number of queries to the database. Basically logs should be buffered in-memory and written in the single query.

2024-03-19 22:46 UTC, morgsmccauley requested changes

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +
🔪

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +  async createLogs (source: string, schemaName: string): Promise<any> {
```suggestion
  async createLogsTable (source: string, schemaName: string): Promise<any> {
```
This seems more clear

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +  }
```suggestion
  }
  
```

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> -
🔪

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +  async addPermissionsToLogsTable (schemaName: string, source: string, tableNames: string[], roleName: string, permissions: string[]): Promise<any> {
This shouldn't be necessary right? `addPermissionsToTables` should pick up the logs tables automatically

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +      CREATE TABLE logs (
I would prefix all created entities with `__`, i.e. `__logs` to:
1. Signify that this is internal/metadata
2. Avoid conflicts with user created entities

2024-03-19 22:46 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +const enum LogLevelNew {
Following on from the sync discussion in the weekly - an extracted `Logging` `class` would be good here.

2024-03-20 17:55 UTC, pkudinov commented on runner/src/hasura-client/hasura-client.ts
> +  }
I wonder if it's worth storing this SQL in a separate SQL file for cleaner code.

2024-03-20 20:28 UTC, Kevin101Zhang commented on runner/src/hasura-client/hasura-client.ts
> +  async addPermissionsToLogsTable (schemaName: string, source: string, tableNames: string[], roleName: string, permissions: string[]): Promise<any> {
Im not too familiar why exactly, but I need the append role here.
<img width="1371" alt="Screenshot 2024-03-20 at 4 27 54 PM" src="https://github.com/near/queryapi/assets/42101107/65ae9369-67d1-402f-a067-6b943e61b07d">

2024-03-21 01:26 UTC, darunrs commented on runner/src/hasura-client/hasura-client.ts
> +  async addPermissionsToLogsTable (schemaName: string, source: string, tableNames: string[], roleName: string, permissions: string[]): Promise<any> {
The append role is a default role Hasura uses to make writes to the default schema tables (state and logs). The role is defined in Indexer here and you can see it is passed into the graphql query function as the role to be used when executing those queries. The reason is that Hasura only allows append and admin to write to these tables. To clarify, this is a **hasura** permission. As far as I can tell, the append role is not an actual Postgres role. Just a virtual role of sorts only recognized by Hasura. 

Regardless, it is not necessary for your logs table to give the append role write access because of two reasons:
1. You can use the user's role to make these writes instead of some generic one like append. 
2. You are making writes to the new logs table through Postgres, not Hasura. As I mentioned earlier, you can't even use append if you wanted to, through Postgres. And we wouldn't want to. We would want to use the user's role since it's in their schema. 

However, we do have the question of how we allow queries to be visible through Hasura (for the frontend). What role does the frontend use for querying logs? Is it append? If so, should we provision a new role which has read access the new logs tables, or reuse append even if append will no longer append anything anymore? 

We'll need to know the answers to those questions and then decide how to structure permissions for roles to read from the new tables. 

Finally, I don't understand why you basically redefined the above addPermissionsToTable function which no changes to its inner code? You can just call the original function again but pass in the append role instead of userRole with whatever permissions it should have.

2024-03-21 01:40 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +  async addPermissionsToLogsTable (schemaName: string, source: string, tableNames: string[], roleName: string, permissions: string[]): Promise<any> {
I'm not sure what the frontend does currently, but going forward we should use the users account ID as the role for accessing logs, just like we do for their other data. This provides a single role for controlling access to the users data - we should view logs as being "owned" by the user and should therefore restricted as such.

Therefore, the existing `addPermissionsToTables` method _should_ work, although it will add `update`/`insert`/`delete`, which may be unwanted given we want to write directly from Postgres.

2024-03-25 20:07 UTC, darunrs requested changes
Nice improvements. Left various comments. I think once you've addressed all of these, you can open up the PR to get full feedback. But, you also need to create a PR for [the infra repo](https://github.com/near/near-ops/tree/master/provisioning/terraform/data_stack/queryapi) to add cron. And make sure that the cron works. Make sure you understand what dependency on infrastructure there is for this code change. If Infra changes need to be released first, don't merge this PR until the infra changes are up.

2024-03-25 20:07 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +                  await this.writeLog(blockHeight, functionName, new Date(), new Date(), 'system', LogLevel.DEBUG, `Inserting object ${JSON.stringify(objectsToInsert)} into table ${tableName}`);
See my other comment about running these in parallel.

2024-03-25 20:07 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +  async writeLog (blockHeight: number, functionName:string, logDate: Date, logTimestamp: Date, logType: string, logLevel: number, ...message: any ): Promise<any> {
As mentioned before, there is no need to have logDate and logTimestamp both.

2024-03-25 20:25 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +    logTimestamp: Date,
Just to confirm the comment here - I should pass a single instance of Date.now() into the writeLog (logTimestamp) and generate logdate from this param?

As opposed to 
` await this.writeLog(blockHeight, functionName, new Date(), new Date(), 'system', LogLevel.DEBUG,  ...log)`
we do
` await this.writeLog(blockHeight, functionName, new Date(), 'system', LogLevel.DEBUG,  ...log)`

and in the logger-class will use the single Date.now() to extrace log-date.

2024-03-25 20:34 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +      db: this.buildDatabaseContext(schemaName, functionName, schema, blockHeight)
Thanks - unsure when this took place.

2024-03-25 21:11 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +    logTimestamp: Date,
Correct. Generate logDate from logTimestamp.

2024-03-26 08:47 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +`;
added space

2024-03-27 07:38 UTC, morgsmccauley requested changes

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer-logger/indexer-logger.ts
> +    const query =
We should be using `pg-format` here to avoid sql injection. It even helps with inserting multiple objects so you wouldn't need to calculate placeholders etc. https://github.com/datalanche/node-pg-format?tab=readme-ov-file#-arrays-and-objects

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer-logger/indexer-logger.ts
> +  formatDate(date: Date): Date {
I'm not sure this conversion is needed - node-postgres will do the [conversion](https://node-postgres.com/features/types#date--timestamp--timestamptz) for us, we can just pass the provided timestamp to both `log_date` and `log_timestamp`

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/__snapshots__/indexer.test.ts.snap
> -exports[`Indexer unit tests Indexer log level respected by writeLog 1`] = `
This removal seems incorrect?

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +        await this.createLogsTable(schemaName, databaseName);
Let's not add side-effects to this method - at surface value, I'd expect `fetchUserApiProvisioningStatus` to tell me whether things have been provisioned correctly, and not act of the fact.

We should "manually" create the `__logs` table for all existing users, making this unnecessary.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +    const ddl = logsTableDDL(source, schemaName);
The logs DDL should be imported in to `Provisioner`, not here. Hasura is just an interface and shouldn't have business specific logic.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +        } else {
This check is actually unnecessary now, it was for an previous migration - we can remove it.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/provisioner/schemas/logs-table.ts
> +CREATE INDEX logs_log_timestamp_idx ON __logs USING btree (log_timestamp);
```suggestion
CREATE INDEX __logs_log_timestamp_idx ON __logs USING btree (log_timestamp);
```
While conflicts are unlikely, I would still prefix this just to signify it's internal

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/provisioner/schemas/logs-table.ts
> +export const logsTableDDL = (source: string, schemaName: string) => `
`source` is not needed, and we can use the pg function `current_schema()` also making `schemaName` unnecessary.

Without the need to inject values I think this would make more sense as a `sql` file.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/stream-handler/stream-handler.ts
> +    indexer.writeLogOld(LogLevel.ERROR, functionName, this.executorContext.block_height,
We should also write to the new logs table

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +  parser: Parser,
Can you run eslint over the project, this comes up as an error.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +          this.indexer_logger = this.indexer_logger ?? IndexerLogger.create(this.database_connection_parameters!);
We should not use `!`, this can lead to runtime errors as we are asserting this is defined, when in fact it can not be.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +          this.writeLogOld(LogLevel.DEBUG, functionName, blockHeight, ...log)
You could probably just call `writeLogOld` from `writeLog` rather than duplicating the calls everywhere.

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +        await Promise.all([...simultaneousPromises, this.indexer_logger?.writeLogBatch(writeLogBatch) ?? Promise.resolve()]);
```suggestion
        await Promise.all([...simultaneousPromises, this.indexer_logger?.writeLogBatch(writeLogBatch)]);
```

2024-03-27 07:38 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +        await Promise.all([...simultaneousPromises, this.indexer_logger?.writeLogBatch(writeLogBatch) ?? Promise.resolve()]);
I think `Promise.all([undefined])` is ok

2024-03-27 17:34 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +    log_level TEXT NOT NULL,
I agree. I'll double check with Eduardo to ensure there won't be any additional compatibility or naming conflicts after removing the "log_" prefixes.

2024-03-27 17:45 UTC, Kevin101Zhang commented on runner/src/hasura-client/hasura-client.ts
> +  async createLogsTable (source: string, schemaName: string): Promise<any> {
Just to confirm, are we using runSql twice.

runSql(logs schema)
runSql(user's schema)

or are we going to combine both ddl to one connection.

runSql(logs schema + user's schema)
    
```
  async runSql (source: string, schemaName: string, userSchemaDDL: string, logsSchemaDDL): Promise<any> {
    return await this.executeSql(
      `
      set schema '${schemaName}';
      ${logsSchemaDDL}
      ${userSchemaDDL}
      `,
      { source, readOnly: false }
    );
  }
```

2024-03-27 18:08 UTC, morgsmccauley commented on runner/src/hasura-client/hasura-client.ts
> +  async createLogsTable (source: string, schemaName: string): Promise<any> {
The first option - `runSql` takes arbitrary sql and executes it

2024-03-27 18:52 UTC, Kevin101Zhang commented on runner/src/provisioner/provisioner.ts
> +        await this.createLogsTable(schemaName, databaseName);
Are you suggesting to remove that code and not to add the logs table for users with an existing provisioned schema, but instead to allow the logs to fail and log a message indicating that the schema does not exist?

2024-03-27 19:14 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +          this.indexer_logger = this.indexer_logger ?? IndexerLogger.create(this.database_connection_parameters!);
Without the assertion, ts will raise an error. How about this?
```
if (this.database_connection_parameters) {
    this.indexer_logger = this.indexer_logger ?? IndexerLogger.create(this.database_connection_parameters);
}
```

2024-03-27 21:55 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +export const logsTableDDL = (source: string, schemaName: string) => `
There is going to be an added layer of complexity since ts ignores files than json / TS and JS. To get that file into output folder on compilation would only work if I follow the instructions in here.

https://stackoverflow.com/questions/65435921/tsconfig-to-copy-sql-file-to-dist
https://github.com/microsoft/TypeScript/issues/30835

2024-03-27 22:01 UTC, morgsmccauley commented on runner/src/provisioner/schemas/logs-table.ts
> +export const logsTableDDL = (source: string, schemaName: string) => `
Fair point, let's leave as `.ts` then 👍🏼

2024-03-27 22:06 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +          this.indexer_logger = this.indexer_logger ?? IndexerLogger.create(this.database_connection_parameters!);
I didn't realise it actually will be defined at this point since we're assigning it on the line above. To work around the TS error your solution is fine, this will also work:
```ts
this.indexer_logger = this.indexer_logger ?? IndexerLogger.create(this.database_connection_parameters as DatabaseConnectionParameters);
```
We can also use nullish assignment, so this would be the same:
```ts
this.indexer_logger ??= IndexerLogger.create(this.database_connection_parameters as DatabaseConnectionParameters);
```

2024-03-30 05:07 UTC, darunrs reviewed
Here's a new round of comments. It's definitely real close to being ready. I also unresolved some comments which were not actually addressed. 

My suggestion is to resolve the comment only after you made that particular code change and committed it locally. Or resolve them after pushing changes up to the PR. This way, you don't lose track of them. Resolving is not necessary to merging a PR, so do what works to ensure they're handled.

2024-03-30 05:07 UTC, darunrs commented on runner/src/provisioner/schemas/logs-table.ts
> +-- GRANT CREATE, USAGE ON SCHEMA cron TO PUBLIC;
You've still got some cron SQL here. Is this no longer necessary after Morgan's PR?

2024-03-30 05:07 UTC, darunrs commented on runner/src/stream-handler/stream-handler.ts
> +      indexer.writeLog({blockHeight: this.executorContext.block_height, logTimestamp: new Date(), logType: LogType.SYSTEM, logLevel: LogLevel.ERROR, message: `Encountered error processing stream: ${t
This is probably the one place where you should still just call writeLog rather than add it to some batch.

2024-03-30 05:10 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +    this.schemaName = functionName.replace(/[^a-zA-Z0-9]/g, '_');
Morgan had a comment about making this a constructor parameter. I agree, you should do that. Expand the comments in the PR and you should see it. I unresolved it.

2024-03-31 00:11 UTC, darunrs commented on runner/src/provisioner/schemas/logs-table.ts
> +export const logsTableDDL = (schemaName: string) => `
You need to add a return type for this function.

2024-03-31 01:58 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +  blockHeight: number;
These semicolons are unnecessary

2024-03-31 01:58 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +
:knife:

2024-03-31 01:58 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +
:knife:

2024-03-31 02:40 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +  parser: Parser,
You still have the issue showing. There's actually all sorts of ESLint errors in this file. Things like improper spacing, unnecessary separators (such as the comma here and the semicolons where you define some interfaces, etc). Please enable proper linting and take a look as it's too many to scour through and mark as comments in this PR.

2024-03-31 19:54 UTC, Kevin101Zhang commented on runner/src/indexer/__snapshots__/indexer.test.ts.snap
>  // Jest Snapshot v1, https://goo.gl/fbAQLP
I dont remember removing this - adding back

2024-03-31 19:59 UTC, Kevin101Zhang commented on   postgres.Dockerfile
> +FROM postgres:14
I just did a git merge and resolved the respective conflicts as Im more comfortable with that workflow to incorporate Morgan's changes

2024-03-31 20:04 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +  parser: Parser,
Got it! Will incorporate eslint more often

2024-03-31 20:08 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.test.ts
> +    it('should create an instance of IndexerLogger with a new PgClient instance if none provided', () => {
ok that makes sense Ill remove the 'create' portion

2024-03-31 20:11 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.test.ts
> +        // Mocking pgClient.query to throw an error
ok that makes sense. Thanks for the insight!

2024-03-31 22:06 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +    log_level TEXT NOT NULL,
morgan and I had a sync to just move forward with it reasoning that it was unlikely to conflict

2024-03-31 22:11 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +        `INSERT INTO %I.__logs (block_height, log_date, log_timestamp, log_type, log_level, message) VALUES %L`,
that makes lots of sense since its redundant and identical now.

2024-03-31 23:15 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +          this.database_connection_parameters = this.database_connection_parameters ?? await this.deps.provisioner.getDatabaseConnectionParameters(hasuraRoleName) as DatabaseConnectionParameters;
done

2024-03-31 23:32 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +    this.schemaName = functionName.replace(/[^a-zA-Z0-9]/g, '_');
Maybe Im a bit confused here but functionName I already modified functionName as a constructors parameter. 
Which then undergoes a sanitization for only non-alphanumeric characters. The sanitized result is stored in this.schemaName.

2024-03-31 23:41 UTC, Kevin101Zhang commented on runner/src/hasura-client/hasura-client.ts
> +  async runSql (source: string, schemaName: string, sqlScript: string): Promise<any> {
its a better name but there's some redundancy since we already have an executeSql method for hasuraClient. Which may lead to confusion. Happy to modify it to an alternative.

2024-04-01 00:27 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +  async writeLogBatch(logEntries: LogEntry[]): Promise<void> {
See comment below:

I can add a trace to the promise in the finally here and this should resolve the writeLogBatch which is now just a writeLog.

```
finally {
        await Promise.all([...simultaneousPromises, this.indexer_logger?.writeLog(logEntries)]);
      }
```

2024-04-01 00:31 UTC, Kevin101Zhang commented
I got some conflicting advice on a sync on thursday with Morgan about keeping the writeLog function but just have writeLogOld call writeLog as oppose to having many instances of promise.all([writeLogOld, writeLog])...

I see the above approach to encapsulate the logging further but indexer_behavior would have to be passed to IndexerLogger. Happy to go with this but just wanted to confirm this is what we want as this leads to some refactoring. We also have some issues with tracing right now as combining both calls writeLog/writeLogBatch in logger have some double tracing but this can be resolved by adding a trace to the finally block in runFunctions.

I think it easiest way to not batch the writeLogs in buildContext unless we declare it as a block scope const and execute it towards the end of the function. Unless we want to move the scoping of our current logEntries or repeatedly pass logEntries as a parameter.

Resolved the other comments.

2024-04-01 20:23 UTC, darunrs commented on runner/src/hasura-client/hasura-client.ts
> +  async runSql (source: string, schemaName: string, sqlScript: string): Promise<any> {
Sure that's fair. In that case, this functionName doesn't accurately represent what it does. It's a wrapper function over executeSql but it does so on a specific schema. So in that case, a better name is `executeSqlOnSchema` or something. runSql just sounds like its a duplicate of executeSql.

2024-04-01 20:30 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +  async writeLogBatch(logEntries: LogEntry[]): Promise<void> {
I don't understand the comment. Are you saying you want to trace this function elsewhere? I'd suggest against that. We can explicitly trace this particular unit of work we care about (writing batch logs) and not need to worry about anything else. If we want to trace other things together, that's out of the scope of this class. I do a similar thing in provisioner, rather than tracing the provisioner chunk of code in Indexer as Indexer's code is bloated enough as it is. I'd like to have Indexer case more about tracing chunks of code, rather than tracing individual function calls. I sort of do the wrong thing with context.db in fact. I should have traced that in DmlHandler. 

What's I'd like to see is something like this:
```
const writeLogsSpan = this.tracer.startSpan('batch write logs');
try {
  await wrapError(DO THE QUERY HERE)
} finally {
  writeLogSpan.end();
}
```

2024-04-01 20:33 UTC, darunrs commented on   postgres.Dockerfile
> +FROM postgres:14
Yeah any approach works, so long as the github PR diff doesn't include work that isn't part of this PR. If adding this postgres file is part of this PR and not work that has been done in someone else's merged commit, then that's all good. Though, I believe Morgan's added this file already. So I should see a diff showing what changes you're making to this file. Not adding a new file, which is now incorrect.

2024-04-02 01:28 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +  async writeLog (logEntry: LogEntry): Promise<any> {
Resolving due to talking async meeting. Migrated logLevel and tracing to logger and writeLog will stay and call writeLogOld.

2024-04-02 01:29 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +  async writeLogBatch(logEntries: LogEntry[]): Promise<void> {
Ahh yeah I have it setup just like this. Was this comment before our sync?

2024-04-02 01:50 UTC, Kevin101Zhang commented on runner/src/stream-handler/stream-handler.ts
> +      indexer.writeLog({blockHeight: this.executorContext.block_height, logTimestamp: new Date(), logType: LogType.SYSTEM, logLevel: LogLevel.ERROR, message: `Encountered error processing stream: ${t
In our newly proposed method - Im going to need to duplicate a function call writeLog to keep this functionality.

2024-04-02 16:28 UTC, darunrs reviewed
Before we push this commit in, we need to run some code to create the logs tables and track them in Hasura. We should do so through a script so that we can duplicate the work in dev and prod with just a change of env variables used. 

I need to recover my local environment a bit but afterward I can write that script up and test it locally. We'll use it on dev and then we can proceed.

2024-04-02 16:28 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +        writeLogSpan.end();
Just to be sure, did you run this locally and check zipkin to see that the traces look correct?

2024-04-02 16:28 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +    const spanMessage = `call writeLog function of IndexerLogger for ${entriesArray.length === 1 ? 'single entry' : `batch of ${entriesArray.length}`}`;
Rename the trace to something like `write batch of {number of logs} logs through postgres`.

2024-04-02 16:30 UTC, darunrs commented on   postgres.Dockerfile
> +FROM postgres:14
So given that Morgan already added this file, let's remove this from the PR then.

2024-04-02 16:31 UTC, darunrs commented on docker-compose.yml
> +  grafana:
Add an empty line at the end of this file

2024-04-02 22:47 UTC, morgsmccauley reviewed
Sorry to create more work. One blocking comment around block height, the rest are just around code cleanliness.

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
>    error: (...log: any[]) => Promise<void>
```suggestion
  debug: (message: string) => Promise<void>
  log: (message: string) => Promise<void>
  warn: (message: string) => Promise<void>
  error: (message: string) => Promise<void>
```

The variadic arguments make the types really awkward - we need to use `any` as we can't guarantee what is passed in. I'm guessing these are only variadic because the original log function was. Since we are adding new methods it may be a good opportunity to just have a single typed argument like so.

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/provisioner/schemas/logs-table.ts
> +    block_height NUMERIC(20) NOT NULL,
Can we make this nullable - some system logs won't necessarily have a block height

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/indexer-logger/indexer-logger.ts
> +    logEntries: LogEntry | LogEntry[],
```suggestion
    logEntries: LogEntry[],
```
Sorry, I know @darunrs already commented on this, but I would just make this take an array only. That way you don't need conditional logic to work with either type. The caller is still free to a single log entry, but it would have to be an array, which I don't think is too inconvenient.

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/indexer-logger/indexer-logger.ts
> +  logTimestamp: Date
From a usability standpoint, I think it's more convenient if we didn't need to pass this in, and instead we create the timestamp within this implementation. This would make the API cleaner and leaves less room for error.

The timestamp would need to correspond to when the `LogEntry` was created, rather than when the `writeLogs` method is called. That way batch logs, which are created ahead of time, would still have the correct timestamp. To achieve this, this could become a class:

```ts
class LogEntry {
  public readonly timestamp: Date;

  constructor (
    public readonly message: string,
    public readonly level: LogLevel,
    public readonly type: LogType,
    public readonly blockHeight?: number
  ) {
    this.timestamp = new Date();
  }

  static systemInfo (message: string, blockHeight?: number): LogEntry {
    return new LogEntry(message, LogLevel.INFO, LogType.SYSTEM, blockHeight);
  }
}
```
Which would be used like so:
```ts
const log = LogEntry.systemInfo('hello');
// later...
writeLog(log);
```

Note that passing an object to `writeLog` directly would still work, as that's all a `class` is really. The `static` methods could be expanded over time to provide convenience.

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/indexer-logger/indexer-logger.ts
> +  logType: string
```suggestion
  logType: LogType
```

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/stream-handler/stream-handler.ts
>  export enum LogLevel {
It feels more appropriate for this to live in `IndexerLogger` now

2024-04-02 22:47 UTC, morgsmccauley commented on runner/src/stream-handler/stream-handler.ts
>    ERROR = 8,
What do these numbers mean? Should we make them strings instead? e.g. `'ERROR'`

2024-04-03 17:51 UTC, darunrs commented on runner/src/indexer-logger/indexer-logger.ts
> +    logEntries: LogEntry | LogEntry[],
I kinda like the suggestion. The reason I went with Type | Type[] for DMlHandler was actually because its user facing and Monaco types can be wonky. So, I wanted to be flexible with the user code. In this case, the callers of this function are us, so we can expect that we write code correctly.

2024-04-03 17:56 UTC, darunrs commented on runner/src/stream-handler/stream-handler.ts
>    ERROR = 8,
This is an optimization I made. We need to compare the incoming log with the log level set in the indexer. So, if the log level was info, we reject debug. If it was error, we reject warn, info, debug. Making the log level a number inside Runner is helpful since I can make that comparison easier by jsut doing LogLevel <= LogLevelConfig.

2024-04-03 18:28 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +    block_height NUMERIC(20) NOT NULL,
@eduohe I dont see any issues with removing this - tagging to confirm

2024-04-03 18:48 UTC, eduohe commented on runner/src/provisioner/schemas/logs-table.ts
> +    block_height NUMERIC(20) NOT NULL,
no problem, we can remove the `NOT NULL` constraint

2024-04-03 19:31 UTC, Kevin101Zhang commented
Focusing on resolving test

2024-04-04 00:13 UTC, Kevin101Zhang commented on runner/src/indexer-logger/indexer-logger.ts
> +  logTimestamp: Date
@morgsmccauley There have been significant modifications in the PR already. Any thoughts on proceeding with the original changes but create a new PR to establish for this update

2024-04-04 00:53 UTC, morgsmccauley requested changes, later dismissed
There are a couple problems with this PR which I've commented inline.

This PR has become massive, and very confusing to track due to the number of comments. That's partly my fault, sorry. This definitely needs more work, but I think it would create more confusion if done here.

I'd recommend merging this with the main functionality commented out:
- Provisioning of the logs table (`runLogsSql()` call in `Provisioner`)
- Flushing the logs to the database (the `writeLogs` call in `Promise.all` in `Indexer`)

That way where not running any new and potentially problematic code, and can make changes to it under the hood.

With the above disabled, functionality should be exactly as it is on `main`. Therefore `indexer.test.ts` and `integration.test.ts` can be reverted to their original state and should pass. That should give us a fair amount of confidence that what we are pushing is not going to break anything.

With all that done, we should collate a list of pending tasks which we can break up in to future smaller PRs.

Let me know if you need help with any of this. I'm happy to sync up.

2024-04-04 00:53 UTC, morgsmccauley commented on runner/tests/integration.test.ts
> +    const mockPgClient = {
The purpose of integration tests are for integrating with real components, can you please remove these mocks.

You can use the `hasuraClient` to get the real DB credentials and inject those in to `IndexerLogger`. Happy to sync up if you need help here.

2024-04-04 00:53 UTC, morgsmccauley commented on runner/src/provisioner/schemas/logs-table.ts
> +CREATE INDEX logs_search_vector_idx ON __logs USING GIN (to_tsvector('english', message));
I thought you prefixed these in an earlier commit but it seems to be gone now?

2024-04-04 00:53 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +          await this.runLogsSql(databaseName, schemaName);
This should be called within `setupPartitionedLogsTable()` and the line below uncommented.

2024-04-04 00:53 UTC, morgsmccauley commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
Could you please add some tests for logging itself? We should assert that the logs themselves actually translate to calls to Postgres

2024-04-04 00:53 UTC, morgsmccauley commented on runner/src/indexer/__snapshots__/indexer.test.ts.snap
> -  ],
This removal means that this (old) log is no called, which is a bug. Do you know why this is the case?

2024-04-04 01:06 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
This is done in indexer-logger.test.ts

2024-04-04 01:08 UTC, morgsmccauley commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
Ah, yes, you're right. But, we're not testing the `IndexerLogger` is actually being used within `Indexer`, i.e. If I have an Indexer which logs message, are we actually calling `IndexerLogger`? That flow is not covered.

2024-04-04 01:08 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +    const mockPgClient = {
Yeah will go ahead and use the real instance here

2024-04-04 01:45 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
It's being covered along with loglevel. there's a specific area in the test called "writeLog is respecting level". Here the we create an indexer and initialize the logger in runfunction. We test to see if the log level is a certain level it calls writeLog in logger.

2024-04-04 02:03 UTC, darunrs reviewed
Super duper close. Some problems with the implementation of testing and some cleanup you can do with the Indexer code.

2024-04-04 02:03 UTC, darunrs commented on runner/src/stream-handler/stream-handler.ts
> +    indexer.callWriteLog({
We should still make the original call, in addition to writeLog. Before this one, please still make the `writeLogOld` call through `indexer`.

2024-04-04 02:03 UTC, darunrs commented on runner/tests/integration.test.ts
> +    const mockPgClient = {
I don't think we're supposed to use mocks in an integration test. That defeats the point. That being said, I don't think this should be a blocker for you to get this PR out as it's gonna take you more time to figure. out usage of this. So, it's ok for now I think. Maybe @morgsmccauley can chime in here.

2024-04-04 02:09 UTC, darunrs commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
No what he means is we check how many times and what logs were given to IndexerLogger in Indexer. 

For example, some tests to verify:

We run an indexer which calls 5 logs, some with debug level with an info config. We then expect that IndexerLogger's writeLogs is called once. And then expect it was called with ALL FIVE LOGS since the filtering is done internally. 

In other words, we don't care if IndexerLogger does the right thing. But we do care if Indexer uses the logger class correctly. So, check scenarios like, the indexer throws an error but we still call writeLogs. Or we call it with all logs produced in various scenarios. Stuff like that.

2024-04-04 04:06 UTC, Kevin101Zhang commented on runner/src/indexer/__snapshots__/indexer.test.ts.snap
> -  ],
Yeah my guess is this is something I missed due to stream handler directly interacting with the writeLogs and forgeting the writeLogsOld. Can go ahead and fix this

2024-04-04 04:16 UTC, Kevin101Zhang commented on runner/src/stream-handler/stream-handler.ts
> +    indexer.callWriteLog({
ah this slipped my mind - readding back - forgetting writeLogOld here is probably the reason the snapshot is missing a small snippert

2024-04-04 19:19 UTC, darunrs commented
Lots of remaining work. so we are going to do a phased rollout of these changes. 

1. We uncommented usage of the new IndexerLogger, but defined it here. All existing tests pass with few modifications and Runner works locally without issue.
2. We are going to modify https://github.com/near/queryapi/pull/636 to conditionally provision the logs table for all indexers. This ensure that we don't have to worry about it again, and we can revert the commit after. 
3. We re-enable usage of IndexerLogger, this time with fully provisioned logs tables. And we can verify the actual functionality works. And we can write up unit tests correctly for that.

2024-04-04 19:21 UTC, darunrs approved these changes

2024-04-04 19:22 UTC, merged

2024-04-04 21:17 UTC, Kevin101Zhang commented on runner/src/provisioner/schemas/logs-table.ts
> +CREATE INDEX logs_search_vector_idx ON __logs USING GIN (to_tsvector('english', message));
'__'

2024-04-04 21:28 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.test.ts
> +    const context = indexer.buildContext(SIMPLE_SCHEMA, INDEXER_NAME, 1, HASURA_ROLE, []);
#4

2024-04-04 21:56 UTC, Kevin101Zhang commented
4 PRs.

1. Fix all unresolved comments in original PR
 - Prefix log indexes with __
 - Move creation of logs table to abstracted function
 - Update LogEntry to be a class
2. Uncomment provisioning of logs, add unit tests in Provisioner, and ensure integration tests pass
3. Ensure auto-provisioning of logs for existing users works, and merge https://github.com/near/queryapi/pull/636
4. Uncomment logging calls, update unit tests in Indexer, and ensure integration tests pass