Enable Logging functionality to both new and old Log Tables
near/queryapi pull request #657
Opened 2024-04-10 20:12 UTC by Kevin101Zhang

https://www.loom.com/share/3ad6d6ea3368412e8896340a74759ffb?sid=4d5379e8-5401-41bf-9e38-d0f8e8c4eca5

2024-04-10 20:20 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +  async callWriteLog (logEntry: LogEntry): Promise<any> {
streamHandler is exclusively using this method if it to directly call writeLogs in case of an error processing the streams. Since streamhandler does not currently have access to an instance of IndexerMeta (we can refactor in the future), we use the indexer that it does have access to and call a helper function to writeLog directly.

2024-04-10 20:51 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.test.ts
> +    expect(provisioner.getDatabaseConnectionParameters).toHaveBeenCalledTimes(3); // todo: temporary fix for the test to ensure new logging works
// todo: temporary fix for the test to ensure new logging functionality all works

this.database_connection_parameters is no longer cached due to getDatabaseConnection is no longer cached

2024-04-10 21:59 UTC, Kevin101Zhang commented
Tackel: https://github.com/near/queryapi/pull/643#discussion_r1560017523

2024-04-11 21:22 UTC, morgsmccauley requested changes

2024-04-11 21:22 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +          // this.database_connection_parameters ??= await this.deps.provisioner.getDatabaseConnectionParameters(hasuraRoleName) as DatabaseConnectionParameters;
We can remove this now right?

2024-04-11 21:22 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
Why do we only call the old logging method if there is a `blockHeight`? Shouldn't we always call it?

2024-04-12 15:31 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
Sorry I should have made a comment here. I only did this if statement as a form of assertion due to the new log table having an optional bh but the old method having a required bh param.

2024-04-14 19:05 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.test.ts
> +    expect(indexerMeta.writeLogs.mock.calls[0][0]).toHaveLength(5);
I aimed to verify the the method calls, but had trouble due to slight timestamp variations. This would be a more thorough test.
```
 expect(jest.fn()).toBeCalledWith(...expected)

    - Expected
    + Received

    @@ -8,30 +8,30 @@
        },
        LogEntry {
          "blockHeight": 456,
          "level": 2,
          "message": "debug log",
    -     "timestamp": 2024-04-14T18:54:21.734Z,
    +     "timestamp": 2024-04-14T18:54:21.735Z,
          "type": "system",
        },
        LogEntry {
          "blockHeight": 456,
          "level": 5,
          "message": "info log",
    -     "timestamp": 2024-04-14T18:54:21.734Z,
    +     "timestamp": 2024-04-14T18:54:21.735Z,
          "type": "system",
        },
        LogEntry {
          "blockHeight": 456,
          "level": 8,
          "message": "error log",
    -     "timestamp": 2024-04-14T18:54:21.734Z,
    +     "timestamp": 2024-04-14T18:54:21.735Z,
          "type": "system",
        },
        LogEntry {
          "blockHeight": 456,
          "level": 2,
          "message": "Selecting objects in table posts with values {\"account_id\":\"morgs_near\",\"receipt_id\":\"abc\"} with no limit",
    -     "timestamp": 2024-04-14T18:54:21.734Z,
    +     "timestamp": 2024-04-14T18:54:21.735Z,
          "type": "system",
        },
      ],
```

2024-04-14 19:22 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +  expect(_logs.length).toEqual(4);
the length of logs from indexer_log_entries and the new logs table (morgs_near_test___logs) should be identical.

2024-04-15 18:05 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +  async getDatabaseConnectionParams (hasuraRoleName: string): Promise<DatabaseConnectionParameters> {
This is not necessary with the changes I've made.

2024-04-15 18:07 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +          this.database_connection_parameters ??= await this.getDatabaseConnectionParams(hasuraRoleName);
Not necessary, due to some updates made to Runner. A successful rebase will allow you to use provisioner's function.

2024-04-15 18:20 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
There's some confusion in your implementation about writeLog and writeLogOld. We ahve two separate functions. Are you trying to have writeLog also call writeLogOld? If so, writeLog should add to the log entries array and then call writeLogOld. And then we call writeLogs function on IndexerMeta at the end. 

Or, if they're supposed to be separate, writeLog should not call writeLogOld. What's your intended implementation? The end result should be that ALL logs are added to the log entries array, and also calling writeLogOld. And then at the end, we run indexerMeta.writeLogs(THE LOGS ARRAY). 

So, pick one:
A. writeLog adds to array, then calls writeLogOld
B. We only have writeLogOld and adding to logEntries.

2024-04-15 18:20 UTC, darunrs commented on runner/tests/integration.test.ts
> +  expect(_logs.length).toEqual(4);
Let's also check the result to see if we see all expected logs. Things like provisioning logs, running function on ... logs. We can ignore the date.

2024-04-15 21:51 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +    expect(provisioning_endpoints.length).toEqual(2);
{
        "message": "Provisioning endpoint: starting"
      },
      {
        "message": "Provisioning endpoint: successful"
      }

2024-04-15 21:57 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +    expect(running_function_enpoint.length).toEqual(2);
We run on 2 blocks
    await indexer.execute(Block.fromStreamerMessage(block115185108 as any as StreamerMessage));
    await indexer.execute(Block.fromStreamerMessage(block115185109 as any as StreamerMessage));

2024-04-15 21:59 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +  expect(_logs.length).toEqual(4);
done I also checked locally if specific columns are null or not. I can add it to the test as well but im not sure if this is necessary as its not done with indexer_log_entries.

2024-04-15 22:13 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
Im confused about this comment here -.

The method writeLog's goal is to append a logEntry into logEntries[] and then call writeLogOld.

within direct block scope of runFunction we have access to both simultaneous promise array and logEntries array as they are declared locally.

Here we just push any log entries to an array for both to later be called in the finally so we do not use the writeLog method at all.


We start using writeLog in the other functional context - buildContext and buildDatabaseContext, originally they were just calling the old writeLog method-> now renamed to writeLogOld. This function has not changed besides the naming and its purpose is to run a graphQLQuery. 

In the current code now we just added a param logEntries to both buildContext and buildDatabaseContext every time we want to write a log as the previous code want we just run it through the new writeLog method which does two things:
1. appends a log entry to the logEntries array to later be resolved in the finally block of runFunctions
2. call the writeLogOld to execute the graphQL query.

2024-04-15 22:15 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
I believe its already doing option A well here unless im missing something

2024-04-15 22:47 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
It looks odd as we explicitly call writeLogOld and then do logEntries.push earlier up (e.g. in Provisioning), and do writeLog() itself later on (e.g. context logs). I suppose this is fine? 

I would like better would be to have writeLog take in a logEntry, a blockheight, logEntries array, and simultaneous promises array. You can add logEntry to the logEntries array (It may or may not have a BH). Then, you can add to simultaneous promises the call to writeLog Old which takes attributes of logEntry along with the passed in block height. This would result in writeLog fully encapsulating all our behavior, allowing us to keep writeLog calls exactly where they were originally while keeping the behavior. We also don't need to worry as much about optional blockheights. This is what I would consider to be a fully implemented option A.

Maybe @morgsmccauley can chime in here if I'm going off the track.

2024-04-16 01:22 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
I understand where you are coming from. If this is permanent code I also believe that it would be great to pass in simultaneousPromises as a Param into buildcontext and builddatabasecontext methods and just push to the respective logEntries/simultaneous promises arrays. This way the functionality is strictly appending entries to be later resolved in the finally block in run functions. But then I thought since this is all temporary and the next PR on sprint would involve removing the hasura writes it did not make sense to continue.

2024-04-16 03:20 UTC, morgsmccauley approved these changes
1 minor comment. Pre-emptively approving on the basis that mine/@darunrs comments are resolved before merging :).

2024-04-16 03:20 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +    if (blockHeight) {
Agree that this is a bit convoluted as we have two implementations going on. I would say let's defer tidying/optimising while this is in flux, and we can clean up once we remove the old implementation.

2024-04-16 03:20 UTC, morgsmccauley commented on runner/tests/integration.test.ts
> +    const { morgs_near_test___logs: _logs }: any = await graphqlClient.request(gql`
```suggestion
    const { morgs_near_test___logs: logs }: any = await graphqlClient.request(gql`
```
The prefix here is really necessary, it's only really important at the DB level

2024-04-16 15:42 UTC, Kevin101Zhang commented on runner/tests/integration.test.ts
> +    const { morgs_near_test___logs: _logs }: any = await graphqlClient.request(gql`
I didn't use this naming due to the above code 
`const { indexer_log_entries: logs }: any = await graphqlClient.request(gql`
what I will do is rename this to `old_logs`. so this can be `logs` as suggested and remove old_logs as apart of the removal PR

2024-04-16 17:44 UTC, darunrs approved these changes
Mostly good. Some comments to address. Can be merged after.

2024-04-16 17:44 UTC, darunrs commented on runner/src/indexer-meta/indexer-meta.test.ts
> +  const indexerConfig = new IndexerConfig('', '', 'some_account/some_indexer', 0, '', '', LogLevel.INFO);
This is the wrong way to use IndexerConfig. You should be passing in the accountID, and then functionName. Not pass in schema name. That is now a generated value based on accountID and function name. Also, you do not need to use underscore sin the names anymore as that's cleaned up as part of the internal behavior. You can do some-account and some-indexer and it will still return some_account/some_indexer as the schema.

2024-04-16 17:44 UTC, darunrs commented on runner/src/indexer-meta/indexer-meta.ts
> +    this.loggingLevel = indexerConfig.logLevel;
This is not necessary. Set indexerConfig as private readonly in the constructor and you can access it using this.indexerConfig. This also allows you to use all of its methods. Just do inline function calls below.

2024-04-16 17:44 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +      await Promise.all([...simultaneousPromises, (this.deps.indexerMeta as IndexerMeta).writeLogs(logEntries)]);
So we have an issue here. Basically, writeLogs could potentially fail because provisioning failed. If that happens, would the error from this Promise.all() lead to the writeLogs writing error overwrite provisioning errors? It's worth having a unit test checking for this behavior as we want the provisioning error to be logged at least to the console, if it's overwritten. If it isn't overwritten, this is fine.

2024-04-16 17:44 UTC, darunrs commented on runner/src/indexer/indexer.ts
> +                  const insertLogEntry = LogEntry.systemDebug(`Inserting object ${JSON.stringify(objectsToInsert)} into table ${tableName}`, blockHeight);
There are not really system logs. They're logs describing stuff that the user is doing. Set them to user logs instead.

2024-04-16 18:50 UTC, Kevin101Zhang commented on runner/src/indexer/indexer.ts
> +      await Promise.all([...simultaneousPromises, (this.deps.indexerMeta as IndexerMeta).writeLogs(logEntries)]);
Yeah thats a good thought - In this case they are not overwritten 

if the provisioning process fails, the error is appropriately handled within a catch on 105-109.
the code structure has provisioning errors immediately logged and handled within that try-catch block there, this is distinct from subsequent logging operations. There shouldnt be a risk of overwriting provisioning errors.

2024-04-16 18:55 UTC, merged

2024-04-16 19:06 UTC, darunrs commented on runner/src/indexer-meta/indexer-meta.ts
> +    this.indexerConfig = indexerConfig;
This is not necessary. Using private readonly will automatically expose indexerConfig to the class as a class variable.