feat: Retry Tracking and Permissions for Tables in Hasura
near/queryapi pull request #663
Opened 2024-04-15 04:18 UTC by darunrs

2024-04-15 23:28 UTC, darunrs commented
Manual testing performed: 
1. Logs and metadata created and tracked, but metadata lacking permissions.
2. Neither created
3. metadata not tracked
4. logs not tracked
5. everything provisioned, tracked, and with permissions

I ran all with multiple blocks to confirm caching behavior works correctly

2024-04-16 00:38 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +  async addPermissionsToTables (indexerSchema: IndexerConfig, tableNames: string[], permissions: string[]): Promise<void> {
I am thinking of refactoring Provisioner to use IndexerConfig as a class variable (passed in during construction) instead of having it passed around all over. Will do that in another PR though, instead of this one. But I did so for this function just for the sake of it.

2024-04-16 00:43 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +          const usersWithPermission = tablePermissions[permisionAttribute] as (HasuraPermissions | undefined);
Not terribly happy that I have to twist TypeScript's arm by asserting the types here so that my forEach loop below doesn't complain about types. Mainly the problem is that the `HasuraTableMetadata` interface has one attribute of type `TableDefinitions`, which causes the `.some()` below get mad since it can't convert `TableDefinitions` into `{ role: string }` format. 

Open to suggestions for how I could potentially clean that up.

2024-04-16 02:28 UTC, morgsmccauley requested changes

2024-04-16 02:28 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +  async provisionLogsAndMetadataIfNeeded (indexerConfig: IndexerConfig): Promise<void> {
So I guess the intention here is that this method will run after the usual `provisionUserApi()`, therefore fixing any Hasura issues if any. But what about existing users who have already been provisioned? This will run standalone, and again, Hasura could have issues leaving us in a bad state.

I guess that is unlikely though since we are only tracking 2 tables: metadata and logs.

2024-04-16 02:28 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +  async provisionLogsAndMetadataIfNeeded (indexerConfig: IndexerConfig): Promise<void> {
Ah, I understand now, this method will continue to run until both all tables are tracked and have roles.

It's a little confusing for this to do both provisioning of logs/metadata _and_ ensure Hasura is consistent. Maybe we can create a new method to do the latter: `ensureConsistentHasuraState()`?

I think that's clearer, but also, when we remove this function, that method can remain.

2024-04-16 02:28 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +            await this.addPermissionsToTables(indexerConfig, needsPermissionsTables, permissionsToAdd);
Will this fail if a table has some of the permissions, i.e. just `select`/`insert`, and not the others? This will attempt to set them again?

2024-04-16 02:28 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +          const userIsLackingPermission = !usersWithPermission?.some((role: { role: string }) => role.role === userName);
I think this would make more sense as `role` rather than `user`?

2024-04-16 02:28 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +    });
It took me a while to grok this code, so I had a play around with it. This structure makes a lot more sense to me, especially the naming. Can we iterate here please? Feel free to adapt the below to what makes sense to you.

```ts
const trackedTablePermissions = await this.getTrackedTablePermissions(indexerConfig);
const untrackedTables = allTableNames.filter((tableName: string) => !trackedTablePermissions.has(tableName));
const tablesWithoutRole = this.getTablesWithoutRole(
  indexerConfig.hasuraRoleName(),
  allTableNames,
  trackedTablePermissions,
  permissionsToAdd
);

if (untrackedTables.length === 0 && tablesWithoutRole.length === 0) {
  provisioningComplete = true;
  return;
}

if (untrackedTables.length > 0) {
  await this.trackTables(indexerConfig.schemaName(), untrackedTables, indexerConfig.databaseName());
}

if (tablesWithoutRole.length > 0) {
  await this.addPermissionsToTables(indexerConfig, tablesWithoutRole, permissionsToAdd);
}
```

```ts
private getTablesWithoutRole (
    roleName: string,
    allTableNames: string[],
    tableMetadata: Map<string, HasuraTableMetadata>,
    permissionsToCheck: Permission[]
  ): string[] {
    return allTableNames.filter((tableName: string) => {
      const tablePermissionMetadata = tableMetadata.get(tableName);
      if (!tablePermissionMetadata) {
        return false;
      }

      return permissionsToCheck.some((permission: string) => {
        const permisionAttribute = `${permission}_permissions` as keyof Omit<HasuraTableMetadata, 'table'>;
        const tablePermissions = tablePermissionMetadata[permisionAttribute];
        // Returns true if the table does not have the permission or the user doesn't have the permission
        const roleExistsForTable = !tablePermissions?.some(({ role }) => role === roleName);
        return roleExistsForTable;
      });
    });
  }
```

2024-04-17 01:47 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +  async provisionLogsAndMetadataIfNeeded (indexerConfig: IndexerConfig): Promise<void> {
Hmm that's a good point. I'll do that!

2024-04-17 19:43 UTC, darunrs commented on runner/src/hasura-client/hasura-client.ts
> +  async getTrackedTablesWithPermissions (
Renamed!

2024-04-17 19:43 UTC, darunrs commented on runner/src/hasura-client/hasura-client.ts
> +  ): Promise<any> {
Added strong types to Hasura. It should fully cover the returned Metadata information.

2024-04-17 19:43 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +  private getTablesMissingTracking (shouldBeTrackedTables: string[], tableMetadata: Map<string, any>): string[] {
Renamed!

2024-04-17 19:44 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +  private getTablesMissingPermissions (
Renamed!

2024-04-17 19:44 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +type Permission = 'select' | 'insert' | 'update' | 'delete';
Moved and renamed to HasuraPermissions.

2024-04-17 19:44 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +          const usersWithPermission = tablePermissions[permisionAttribute] as (HasuraPermissions | undefined);
Went ahead with Omit for now. Thanks for the suggestion! I believe I fixed the spelling mistakes too haha.

2024-04-17 19:45 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +          const userIsLackingPermission = !usersWithPermission?.some((role: { role: string }) => role.role === userName);
Yeah I suppose that's true. I'll rename it.

2024-04-17 19:52 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +            await this.addPermissionsToTables(indexerConfig, needsPermissionsTables, permissionsToAdd);
I did not cover partial failures of adding permissions. The current code just expects it to be a all or none. I did configure the code to accept different lists of permissions (even though we currently set all of them). I felt like that was something we can potentially cover in the future rather than now.

2024-04-18 00:34 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +    });
Refactored the code to be easier to understand. Thanks for the call out!

2024-04-18 00:55 UTC, darunrs commented on runner/src/provisioner/provisioner.test.ts
> +function generateTableConfig (schemaName: string, tableName: string, role: string, permissionsToAdd: HasuraPermission[]): HasuraTableMetadata {
How weird would it be to export a function from a test class? Both of these benefit from a function which generates metadata .

2024-04-18 01:32 UTC, morgsmccauley approved these changes

2024-04-18 01:32 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.ts
> +      return this.roleLacksPermission(roleName, tablePermissionsMetadata[permissionAttribute]);
Isn't this really `tablePermissionsLackRole`?

2024-04-18 01:32 UTC, morgsmccauley commented on runner/src/provisioner/provisioner.test.ts
> +function generateTableConfig (schemaName: string, tableName: string, role: string, permissionsToAdd: HasuraPermission[]): HasuraTableMetadata {
Kinda weird, personally I'd prefer it went in a `test-utils` file or something. I think the duplication is fine though 🤔

2024-04-18 01:32 UTC, morgsmccauley commented on runner/src/indexer/indexer.ts
> +        await this.deps.provisioner.ensureConsistentHasuraState(this.indexerConfig);
Eventually I think we should put this within `provisionUserApi()` and have it retry, but is probably fine living here for now

2024-04-18 17:47 UTC, darunrs commented on runner/src/provisioner/provisioner.test.ts
> +function generateTableConfig (schemaName: string, tableName: string, role: string, permissionsToAdd: HasuraPermission[]): HasuraTableMetadata {
Fair enough. Maybe if we end up with more I'll make a shared utils file.

2024-04-18 17:47 UTC, darunrs commented on runner/src/provisioner/provisioner.ts
> +      return this.roleLacksPermission(roleName, tablePermissionsMetadata[permissionAttribute]);
True. That's a better name.

2024-04-18 19:22 UTC, merged