feat: display the number of queries in the past 7 days on each indexer card in the dashboard
near/queryapi pull request #837
Opened 2024-06-25 20:46 UTC by Kevin101Zhang

2024-06-25 20:49 UTC, Kevin101Zhang commented
<img width="1005" alt="Screenshot 2024-06-25 at 4 49 05 PM" src="https://github.com/near/queryapi/assets/42101107/50202ead-6d07-40f1-90b6-46bfbf702c9c">

2024-07-09 22:33 UTC, morgsmccauley commented on frontend/widgets/src/QueryApi.IndexerExplorer.jsx
> +  const url = 'https://storage.googleapis.com/databricks-near-query-runner/output/query-api-usage/indexers.json';
Probably need to make this an environment variable, and use the dev endpoint when it's ready

2024-07-12 18:16 UTC, Kevin101Zhang commented on frontend/widgets/src/QueryApi.IndexerExplorer.jsx
> +  const url = 'https://storage.googleapis.com/databricks-near-query-runner/output/query-api-usage/indexers.json';
done

2024-07-12 20:45 UTC, eduohe requested changes, later dismissed

2024-07-12 20:45 UTC, eduohe commented on frontend/widgets/src/QueryApi.IndexerCard.jsx
> +const { accountId, indexerName, lastDeploymentDate, numDeployements, numQueries, originalDeploymentDate } = props;
I think we need to show `originalDeploymentDate` in the card too

2024-07-15 22:11 UTC, Kevin101Zhang commented on frontend/widgets/src/QueryApi.IndexerCard.jsx
> +const { accountId, indexerName, lastDeploymentDate, numDeployements, numQueries, originalDeploymentDate } = props;
I belive this is more for internal use. Clarified with pavel

2024-07-15 22:11 UTC, merged